#===============
# World Bank RBF
# Engagement Lab, 2015
# -------------
# Phase Two Content Configuration
# ==============

# The time it takes for a tactic card to be spawned (one of these is chosen at random to queue the next card)
# tactic_card_intervals: [15, 20, 35]
tactic_card_intervals: [5, 5, 5]

# The length of a month
month_length_seconds: 25