#===============
# World Bank RBF
# Engagement Lab, 2015
# -------------
# Content Configuration
# ==============

private: true

# All cooldowns are in seconds
cooldown:
  short: [5, 5, 10]
  long: [120, 200, 350]