#===============
# World Bank RBF
# Engagement Lab, 2015
# -------------
# Route Definitions
# ==============

- symbol: capitol_to_malcom
  city1: capitol
  city2: malcom
  unlocked: true
  speed: 30
  cost: 2

- symbol: capitol_to_crup
  city1: capitol
  city2: crup
  unlocked: true
  speed: 30
  cost: 1

- symbol: crup_to_kibari
  city1: crup
  city2: kibari
  unlocked: false
  speed: 30
  cost: 2

- symbol: malcom_to_valeria
  city1: malcom
  city2: valeria
  unlocked: false
  speed: 50
  cost: 1

- symbol: malcom_to_kibari
  city1: malcom
  city2: kibari
  unlocked: false
  speed: 30
  cost: 2

- symbol: malcom_to_mile
  city1: malcom
  city2: mile
  unlocked: true
  speed: 30
  cost: 2

- symbol: valeria_to_zima
  city1: valeria
  city2: zima
  unlocked: false
  speed: 60
  cost: 1

- symbol: zima_to_kibari
  city1: zima
  city2: kibari
  unlocked: false
  speed: 15
  cost: 3

- symbol: kibari_to_mile
  city1: kibari
  city2: mile
  unlocked: false
  speed: 40
  cost: 1

- symbol: mile_to_zima
  city1: mile
  city2: zima
  unlocked: true
  speed: 30
  cost: 2
