#===============
# World Bank RBF
# Engagement Lab, 2015
# -------------
# Route Definitions
# ==============

- symbol: capitol_to_malcom
  city1: capitol
  city2: malcom
  unlocked: true
  speed: 30
  cost: 2
  #Train#


- symbol: capitol_to_crup
  city1: capitol
  city2: crup
  unlocked: true
  speed: 30
  cost: 1
  #Bus#


- symbol: crup_to_kibari
  city1: crup
  city2: kibari
  unlocked: false
  speed: 30
  cost: 2
  #Bus#


- symbol: malcom_to_valeria
  city1: malcom
  city2: valeria
  unlocked: false
  speed: 30
  cost: 1
  #Bus#



- symbol: malcom_to_kibari
  city1: malcom
  city2: kibari
  unlocked: false
  speed: 30
  cost: 2
  #fruit truck#


- symbol: malcom_to_mile
  city1: malcom
  city2: mile
  unlocked: true
  speed: 30
  cost: 2
  #train#



- symbol: valeria_to_zima
  city1: valeria
  city2: zima
  unlocked: false
  speed: 30
  cost: 1
  #airship#


- symbol: zima_to_kibari
  city1: zima
  city2: kibari
  unlocked: false
  speed: 30
  cost: 3
  #Fruit truck#



- symbol: kibari_to_mile
  city1: kibari
  city2: mile
  unlocked: false
  speed: 30
  cost: 1
  #fruit truck#

- symbol: mile_to_zima
  city1: mile
  city2: zima
  unlocked: true
  speed: 30
  cost: 2
  #train#
