#===============
# World Bank RBF
# Engagement Lab, 2015
# -------------
# Phase Two Scenario One Path Config YAML
# ==============

prompt_year_1: 
  - "Now that the year is over, you have the option to alter the program by terminating a provider's contract. Do you want to terminate the clinic manager's contract and replace them with a new provider?"
  - "Now that the year is over, you have the option to alter the program by terminating a provider's contract. Do you want to terminate the clinic manager's contract and replace them with a new provider?"
  - "Now that the year is over, you have the option to alter the program by terminating a provider's contract. Do you want to terminate the clinic manager's contract and replace them with a new provider?"

prompt_year_2: 
  - "Now that the year is over, you have the option to alter the program by terminating a provider's contract. Do you want to terminate the clinic manager's contract and replace them with a new provider?"
  - "Now that the year is over, you have the option to alter the program by terminating a provider's contract. Do you want to terminate the clinic manager's contract and replace them with a new provider?."
  - "Now that the year is over, you have the option to alter the program by terminating a provider's contract. Do you want to terminate the clinic manager's contract and replace them with a new provider?"

prompt_year_2_twist: 
  - "You have one more year to go before we see if you have met your goals. If you are having complications with this new traditional clinic manager, we do have another provider at the ready. Would you like to replace him?"
  - "You have one more year to go before we see if you have met your goals. If you are having complications with this new traditional clinic manager, we do have another provider at the ready. Would you like to replace him?"
  - "You have one more year to go before we see if you have met your goals. If you are having complications with this new traditional clinic manager, we do have another provider at the ready. Would you like to replace him?"

choices: # <---- The choices the player will see during a year break.
  - text: "Replace Clinic Manager with new provider"
    # This instructs the game to load the player into twist 1 if at end of year 1.
    # At end of year 2, it would load year 3's twist 1 OR 2 depending on if the player chose an option at end of year 1.
    # This can also be a scenario, e.g. "scenario_4", in which case the player is brought to the specified scenario, with its *default* problems loaded.
    load: "twist" 

choices_twist:
  - text: "Replace Mr. Todd with new provider"
    # This instructs the game to load the player into twist 1 if at end of year 1.
    # At end of year 2, it would load year 3's twist 1 OR 2 depending on if the player chose an option at end of year 1.
    # This can also be a scenario, e.g. "scenario_4", in which case the player is brought to the specified scenario, with its *default* problems loaded.
    load: "twist" 
