#===============
# World Bank RBF
# Engagement Lab, 2015
# -------------
# Phase Two Scenario One Path Config YAML
# ==============

prompt_year_1: 
  - "Now that the year's over, you have the option to alter the program. Do you think the program should explicitly grant providers more autonomy? Review your work from the past year and decide."
  - "Now that the year's over, you have the option to alter the program. Do you think the program should explicitly grant providers more autonomy? Review your work from the past year and decide."
  - "Now that the year's over, you have the option to alter the program. Do you think the program should explicitly grant providers more autonomy? Review your work from the past year and decide."

prompt_year_2: 
  - "Now that the year's over, you have the option to alter the program. Do you think the program should explicitly grant providers more autonomy? Review your work from the past year and decide."
  - "Now that the year's over, you have the option to alter the program. Do you think the program should explicitly grant providers more autonomy? Review your work from the past year and decide."
  - "Now that the year's over, you have the option to alter the program. Do you think the program should explicitly grant providers more autonomy? Review your work from the past year and decide."

choices: # <---- The choices the player will see during a year break.
  - text: "Grant Providers Autonomy"
    # This instructs the game to load the player into twist 1 if at end of year 1.
    # At end of year 2, it would load year 3's twist 1 OR 2 depending on if the player chose an option at end of year 1.
    # This can also be a scenario, e.g. "scenario_4", in which case the player is brought to the specified scenario, with its *default* problems loaded.
    load: "scenario_1" 

