#!/bin/sh
#/etc/init.d/apiprod

export PATH=$PATH:/usr/bin
export NODE_PATH=$NODE_PATH:/usr/lib/node_modules
export NODE_ENV=production

case "$1" in
  start)
  exec sudo NODE_ENV=production forever start --sourceDir=/srv/api/server -p /usr/lib/node_modules/forever -o out.log -e err.log -c "npm start" ./
  ;;
stop)
  PROCESS_ID=$(forever list | grep 'npm' | awk '{print $7}')
  exec sudo forever stop $PROCESS_ID
  ;;
list)
  PROCESSES="$(forever list | grep npm)"
  echo $PROCESSES
  ;;
*)
  echo "Usage: /etc/init.d/apiprod {start|stop|list}"
  exit 1
  ;;
esac