#===============
# World Bank RBF
# Engagement Lab, 2015
# -------------
# Phase Two Scenario One Path Config YAML
# ==============

prompt_year_1: 
  - "You did nothing!!"
  - "Thank you for joining us for the end of year meeting. It seems like your program implementation is going smoothly, yes? That said, we would like to know if you need anything approved through us to make the program run more efficiently. It seems like your program is running quite well, but there is always opportunity for slight modification."
  - "Good Job!"

prompt_year_2: 
  - "You did nothing!!"
  - "You've made it to the end of year two. I hope you are checking your indicators and making sure the RBF program is running smoothly. Is there anything you need from us? If the new Clinic Manager is not working out we can make internal adjustments."
  - "Good Job!"

choices: # <---- The choices the player will see during a year break.
  - text: "Now that the year is over, you have the option to alter the program by terminating a provider's contract. Do you want to terminate the clinic manager's contract and replace them with a new provider? Take a look at your work from the past year and decide."
    # This instructs the game to load the player into twist 1 if at end of year 1.
    # At end of year 2, it would load year 3's twist 1 OR 2 depending on if the player chose an option at end of year 1.
    # This can also be a scenario, e.g. "scenario_4", in which case the player is brought to the specified scenario, with its *default* problems loaded.
    load: "twist" 

