#===============
# World Bank RBF
# Engagement Lab, 2015
# -------------
# Phase Two Content Configuration
# ==============

# The time it takes for a tactic card to be spawned (one of these is chosen at random to queue the next card)
# tactic_card_intervals: [15, 20, 35]
tactic_card_intervals: [5, 5, 5]

# The length of phase two
phase_length_seconds: 900

# The array of tactic symbols that correspond to supervisor "tactics" problems, if the tactic is not part of player's selected plan
tactics_not_selected: 
  - unlockable_improve_patient_and_provider_relationship_not_selected
  - unlockable_information_campaign_to_explain_changes_to_system
  - unlockable_incentivise_providers_to_follow_protocols

# Prompt for end of game
prompt_year_3: 
  - "Unfortunately we did not meet our goals. Vaccination rates, facility births, and overall quality of care all fell short. You can return to the main menu to try again or implement a new program."
  - "You did some good, but unfortunately we fell short on most of our goals. We're encouraged by some of your results. Try implementing a different program, or designing a new one."
  - "Good work! You met or exceeded two of the three goals, but we believe you can do better. Try Implementing a different program, or designing a new one."
  - "Amazing! You exceeded all of your goals for vaccination rates, facility births, and overall quality of care. You have proven that this approach was the right choice."